<?php
// $Id$

/**
 *  将数组转换为 excel，保存为文件或直接输出下载 
 * @param array $header 
 *  表头，确定 excel 的列数
 *    如： array('name' => '名称', 'city' => '城市');
 *    指定每列的数据格式，如：
 *      array(
 *        'name' => array('data' => '名称', 'type' => 'string')
 *      )
 * @param array $data 
 *  多行数据，每行键名需与 $header 对应，如：
 *    array(
 *      array('name' => '张三', 'city' => array('data' => '上海', 'type' => 'string')),
 *      array('name' => '李四', 'city' => '北京'),
 *    )
 *  如数字键名，将与 header 按顺序对应
 *    array(
 *      array('张三', '中国'),
 *      array('李四', '北京'),
 *    );
 * @param string $filepath 
 *  文件路径，若有，则保存为文件
 * @param array $values 
 *  excel 文档的基本信息
 * @param string $version 
 *  excel 版本，默认为 excel 2003
 * @access public
 * @return void
 */
function phpExcel_data_to_excel($header, $data, $filepath = NULL, $values = array(), $version = 'Excel2007') {
  static $is_load;

  if (!isset($is_load)) {
    $classes = DIDA_ROOT . '/' . dd_get_path('module', 'phpExcel') . '/Classes/PHPExcel.php';
    if (is_file($classes)) {
      require_once $classes;
      $is_load = true;
    } else {
      dd_set_message(t('phpExcel', '缺少 PHPExcel 类文件，请阅读模块说明文件'), 'error');
    }
  }

//  if (!isset($cached)) {
//    $cacheMethod = PHPExcel_CachedObjectStorageFactory::cache_to_memcache;  
//    $cacheSettings = array(
//      'memcacheServer' => 'localhost',  
//      'memcachePort' => 11211,  
//      'cacheTime' => 600
//    );
//    PHPExcel_Settings::setCacheStorageMethod($cacheMethod, $cacheSettings); 
//    $cached = true;
//  }

  $default_value = array(
    'Creator' => 'Dida', // 作者
    'LastModifiedBy' => 'Dida', // 最后更新
    'Subject' => '', // 文档主题
    'Title' => 'Dida Excel', // 文档标题
    'Description' => 'Dida Excel', // 描述
    'Keywords' => 'Dida', // 关键词
    'Category' => 'Dida', // 类别
  );

  $values = array_merge($default_value, $values);

  if (empty($values['Subject'])) $values['Subject'] = $values['Title'];

  $excel = new PHPExcel();

  // 定义表格基本列：A B C D .. Z
  $keys = range('A', 'Z');

  $_j = 0; 

  // 超过 26 列，扩展
  while (count($keys) < count($header)) {
    for ($_k = 0; $_k < 26; $_k++) {
      // AA AB AC AD
      // BA BB BC BD
      $keys[] =  $keys[$_j] . $keys[$_k];
    }
    $_j++;
  }
  
  $rows = array();
  
  $i = 0;
  foreach ($header as $key => $value) {
    
    if (!is_array($value)) $value = array('data' => $value);

    $excel->setActiveSheetIndex(0)->setCellValue($keys[$i] . '1', $value['data']);
    $rows[$key] = $value;
    $rows[$key]['data'] = $keys[$i];
    
    // 列宽度
    if (!empty($value['width'])) {
      $excel->getActiveSheet()->getColumnDimension($keys[$i])->setWidth($value['width']); 
    }

    // 自动换行
    if (!empty($value['wrap'])) {
      $excel->getActiveSheet()->getStyle($keys[$i])->getAlignment()->setWrapText(true);
    }
    ++$i;
  }
  
  // 写入文档基本信息
  $i = 2;

  $types = phpExcel_get_data_type();

  $keys = array_keys($rows);
  
  foreach ($data as  $doc) {
    if (is_array($doc) || is_object($doc)) {
      $j = 0;
      foreach ($doc as $key => $value) {
        // 若是数字递增键名，按顺序与 header 对应 
        if (is_numeric($key)) $key = $keys[$j];
        
        $j++;

        if (empty($rows[$key])) continue;
        
        if ($i%2 == 0) {
          if (!empty($rows[$key]['even'])) {
            $color = $rows[$key]['even'];
          } else {
            $color = 'FFFFFF';
          }
        } else {
          if (!empty($rows[$key]['odd'])) {
            $color = $rows[$key]['odd'];
          } else {
            $color = 'E8E8E8';
          }
        }

        // 设置颜色
        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getFill()->getStartColor()->setRGB($color);

        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getLeft()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
        $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getRight()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

        //$excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getTOP()->getColor()->setRGB('FF0000');
        //$excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getBorders()->getBottom()->getColor()->setRGB('FF0000');
        
        if (!empty($rows[$key]['wrap'])) {
          $excel->getActiveSheet()->getStyle($rows[$key]['data'] . $i)->getAlignment()->setWrapText(true);
        }

        if (!is_array($value)) {
          if (empty($rows[$key]['type'])) {
            $excel->setActiveSheetIndex(0)->setCellValue($rows[$key]['data'] . $i, $value);
          } else {
            $value = array('data' => $value, 'type' => $rows[$key]['type']);
            $excel->setActiveSheetIndex(0)->setCellValueExplicit($rows[$key]['data'] . $i, $value['data'], $types[$value['type']]);
          }
        } else if (!empty($value['data'])) {
          if (empty($value['type']) && !empty($rows[$key]['type'])) {
            $value['type'] = $rows[$key]['type'];
          }
          $excel->setActiveSheetIndex(0)->setCellValueExplicit($rows[$key]['data'] . $i, $value['data'], $types[$value['type']]);
        } else {
          $excel->setActiveSheetIndex(0)->setCellValue($rows[$key]['data'] . $i, '');
        } 
      }
      ++$i;
    }
  }
  
  $excel->setActiveSheetIndex(0);

  // Excel5 或 Excel2007
  $objWriter = PHPExcel_IOFactory::createWriter($excel, $version);

  // 写入文件
  if (!empty($filepath)) {
    $filename = basename($filepath);
    if ($path = file_mkdir(dirname($filepath))) {
      $objWriter->save($path . '/' . $filename);
      return true;
    }
  } else {
    // 输出下载
    if ($version == 'Excel5') {
      header('Content-Type: application/vnd.ms-excel; charset=utf-8');
      $values['Title'] .= '.xls';
    } else {
      header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      $values['Title'] .= '.xlsx';
    }
    header('Content-Disposition: attachment;filename="' . $values['Title'] . '"');
    header('Cache-Control: max-age=0');
    $objWriter->save('php://output');
    exit;
  }
}

/**
 * 数据类型 
 * @param string $key 
 * @access public
 * @return array|*
 */
function phpExcel_get_data_type($key = '') {
  $types = array(
    'string' => PHPExcel_Cell_DataType::TYPE_STRING, // 字符串
    'null' => PHPExcel_Cell_DataType::TYPE_NULL,
    'formula' => PHPExcel_Cell_DataType::TYPE_FORMULA, // 公式
    'bool' => PHPExcel_Cell_DataType::TYPE_BOOL,
    'error' => PHPExcel_Cell_DataType::TYPE_ERROR,
  );

  return $key ? $types[$key] : $types;
}

